[package]
name = "zkstark_amaci_tally"
version = "0.1.0"
edition = "2024_07"

[cairo]
enable-gas = false

[dependencies]
cairo_execute = "2.18.0"

[dev-dependencies]
cairo_test = "2.18.0"

[lib]
sierra = true
casm = true

[[target.executable]]
name = "tally_votes_native"
function = "zkstark_amaci_tally::native_tally_votes::main"

[[target.executable]]
name = "tally_votes_native_stone"
function = "zkstark_amaci_tally::stone_native_tally_votes::tally_votes_native_stone_main"

[[target.executable]]
name = "add_new_key_native"
function = "zkstark_amaci_tally::native_add_new_key::add_new_key_native_main"

[[target.executable]]
name = "process_messages_native_boundary"
function = "zkstark_amaci_tally::native_process_messages::process_messages_native_boundary_main"

[[target.executable]]
name = "process_message_coord_key_native"
function = "zkstark_amaci_tally::native_process_message_components::process_message_coord_key_native_main"

[[target.executable]]
name = "process_message_ecdh_native"
function = "zkstark_amaci_tally::native_process_message_components::process_message_ecdh_native_main"

[[target.executable]]
name = "process_message_decrypt_native"
function = "zkstark_amaci_tally::native_process_message_components::process_message_decrypt_native_main"

[[target.executable]]
name = "process_message_signature_native"
function = "zkstark_amaci_tally::native_process_message_components::process_message_signature_native_main"

[[target.executable]]
name = "process_message_step_core_native"
function = "zkstark_amaci_tally::native_process_message_step_core::process_message_step_core_native_main"

[[target.executable]]
name = "process_deactivate_native_boundary"
function = "zkstark_amaci_tally::native_process_deactivate::process_deactivate_native_boundary_main"

[[target.executable]]
name = "process_deactivate_coord_key_native"
function = "zkstark_amaci_tally::native_process_deactivate_components::process_deactivate_coord_key_native_main"

[[target.executable]]
name = "process_deactivate_ecdh_native"
function = "zkstark_amaci_tally::native_process_deactivate_components::process_deactivate_ecdh_native_main"

[[target.executable]]
name = "process_deactivate_signature_native"
function = "zkstark_amaci_tally::native_process_deactivate_components::process_deactivate_signature_native_main"

[[target.executable]]
name = "process_deactivate_decrypt_native"
function = "zkstark_amaci_tally::native_process_deactivate_components::process_deactivate_decrypt_native_main"

[[target.executable]]
name = "process_deactivate_step_core_native"
function = "zkstark_amaci_tally::native_process_deactivate_step_core::process_deactivate_step_core_native_main"
