#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

usage() {
  cat <<'EOF'
Usage:
  tools/run-stone-proof.sh [--air-run <stone-air-run.json>] [--out-dir <dir>] [options]

Runs Stone cpu_air_prover over AIR files generated by tools/run-stone-air.sh,
then verifies the proof locally with cpu_air_verifier.

Options:
  --air-run <path>          stone-air-run.json. Default: target/stone-air/tally/stone-air-run.json
  --out-dir <dir>           Output directory. Default: sibling directory "stone-proof" next to --air-run
  --stone-prover-dir <dir>  Stone prover checkout. Default: $STONE_PROVER_DIR or ~/stone-prover
  --prover-config <path>    cpu_air_prover_config.json. Auto-detected if omitted.
  --parameter-file <path>   cpu_air_params.json. Auto-detected if omitted.
  --skip-verify             Skip cpu_air_verifier.

Outputs:
  stone-proof.json
  stone-prove.log
  stone-verify.log
  proof-run.json
EOF
}

require_tool() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "$1 is required" >&2
    exit 1
  fi
}

json_field() {
  local file="$1"
  local field="$2"
  node -e '
const fs = require("fs");
const [file, field] = process.argv.slice(1);
const json = JSON.parse(fs.readFileSync(file, "utf8"));
const value = json[field];
if (typeof value !== "string" || value.length === 0) {
  process.exit(2);
}
process.stdout.write(value);
' "$file" "$field"
}

validate_air_layout() {
  local public_input_file="$1"
  node - "$public_input_file" <<'NODE'
const fs = require('fs');
const publicInputFile = process.argv[2];
const json = JSON.parse(fs.readFileSync(publicInputFile, 'utf8'));
const layout = String(json.layout ?? '');
const segments = json.mem_segment_addresses ?? {};
const missing = [];

if (layout === 'all_cairo' || layout === 'all_cairo_stwo') {
  for (const segment of ['add_mod', 'mul_mod']) {
    if (!Object.prototype.hasOwnProperty.call(segments, segment)) {
      missing.push(segment);
    }
  }
}

if (missing.length > 0) {
  console.error(
    `Stone AIR layout '${layout}' is missing builtin segment(s): ${missing.join(', ')}.`
  );
  console.error('Regenerate the AIR with a layout that matches this tally wrapper, for example:');
  console.error('  npm run stone:air:tally -- --out-dir <new-dir> --layout recursive');
  console.error('Then rerun stone:prove:tally against the new stone-air-run.json.');
  process.exit(2);
}
NODE
}

resolve_stone_config_file() {
  local explicit_path="$1"
  local file_name="$2"
  local candidates=()

  if [[ -n "$explicit_path" ]]; then
    candidates+=("$explicit_path")
  else
    candidates+=(
      "$STONE_PROVER_DIR/$file_name"
      "$STONE_PROVER_DIR/e2e_test/Cairo/$file_name"
      "$STONE_PROVER_DIR/e2e_test/CairoZero/$file_name"
    )

    if [[ -n "${INTEGRITY_DIR:-}" ]]; then
      candidates+=("$INTEGRITY_DIR/examples/proofs/$file_name")
    fi
    if [[ -n "${HOME:-}" ]]; then
      candidates+=("$HOME/integrity/examples/proofs/$file_name")
    fi
  fi

  local candidate
  for candidate in "${candidates[@]}"; do
    if [[ -f "$candidate" ]]; then
      printf '%s/%s\n' "$(cd "$(dirname "$candidate")" && pwd)" "$(basename "$candidate")"
      return 0
    fi
  done

  echo "${explicit_path:-$STONE_PROVER_DIR/$file_name}"
  return 1
}

AIR_RUN_JSON=""
OUT_DIR=""
STONE_PROVER_DIR="${STONE_PROVER_DIR:-$HOME/stone-prover}"
PROVER_CONFIG_FILE=""
PARAMETER_FILE=""
SKIP_VERIFY=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --air-run)
      AIR_RUN_JSON="${2:-}"
      shift 2
      ;;
    --out-dir)
      OUT_DIR="${2:-}"
      shift 2
      ;;
    --stone-prover-dir)
      STONE_PROVER_DIR="${2:-}"
      shift 2
      ;;
    --prover-config)
      PROVER_CONFIG_FILE="${2:-}"
      shift 2
      ;;
    --parameter-file)
      PARAMETER_FILE="${2:-}"
      shift 2
      ;;
    --skip-verify)
      SKIP_VERIFY=1
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

AIR_RUN_JSON="${AIR_RUN_JSON:-$ROOT_DIR/target/stone-air/tally/stone-air-run.json}"
AIR_RUN_JSON="$(cd "$(dirname "$AIR_RUN_JSON")" && pwd)/$(basename "$AIR_RUN_JSON")"

if [[ ! -f "$AIR_RUN_JSON" ]]; then
  echo "missing Stone AIR metadata: $AIR_RUN_JSON" >&2
  echo "run npm run stone:air:tally first" >&2
  exit 1
fi

OUT_DIR="${OUT_DIR:-$(dirname "$AIR_RUN_JSON")/stone-proof}"
mkdir -p "$OUT_DIR"
OUT_DIR="$(cd "$OUT_DIR" && pwd)"

if [[ -d "$STONE_PROVER_DIR" ]]; then
  STONE_PROVER_DIR="$(cd "$STONE_PROVER_DIR" && pwd)"
fi
PROVER_CONFIG_FILE="$(resolve_stone_config_file "$PROVER_CONFIG_FILE" cpu_air_prover_config.json || true)"
PARAMETER_FILE="$(resolve_stone_config_file "$PARAMETER_FILE" cpu_air_params.json || true)"

require_tool node
require_tool cpu_air_prover
if [[ "$SKIP_VERIFY" -ne 1 ]]; then
  require_tool cpu_air_verifier
fi

if [[ ! -f "$PROVER_CONFIG_FILE" ]]; then
  echo "missing prover config file: $PROVER_CONFIG_FILE" >&2
  echo "pass --prover-config or set STONE_PROVER_DIR to a Stone checkout" >&2
  exit 1
fi

if [[ ! -f "$PARAMETER_FILE" ]]; then
  echo "missing parameter file: $PARAMETER_FILE" >&2
  echo "pass --parameter-file or set STONE_PROVER_DIR to a Stone checkout" >&2
  exit 1
fi

AIR_PUBLIC_INPUT="$(json_field "$AIR_RUN_JSON" airPublicInput)"
AIR_PRIVATE_INPUT="$(json_field "$AIR_RUN_JSON" airPrivateInput)"
PREPARED_JSON="$(json_field "$AIR_RUN_JSON" preparedJson)"
INPUT_PATH="$(json_field "$AIR_RUN_JSON" inputPath)"
EXECUTABLE="$(json_field "$AIR_RUN_JSON" executable)"
RUNNER_SIERRA_JSON="$(json_field "$AIR_RUN_JSON" runnerSierraJson)"

if [[ ! -f "$AIR_PUBLIC_INPUT" ]]; then
  echo "missing AIR public input: $AIR_PUBLIC_INPUT" >&2
  exit 1
fi

if [[ ! -f "$AIR_PRIVATE_INPUT" ]]; then
  echo "missing AIR private input: $AIR_PRIVATE_INPUT" >&2
  exit 1
fi

validate_air_layout "$AIR_PUBLIC_INPUT"

PROOF_JSON="$OUT_DIR/stone-proof.json"
PROVE_LOG="$OUT_DIR/stone-prove.log"
VERIFY_LOG="$OUT_DIR/stone-verify.log"
PROOF_RUN_JSON="$OUT_DIR/proof-run.json"

echo "==> Proving Stone tally AIR"
echo "AIR run: $AIR_RUN_JSON"
echo "prover config: $PROVER_CONFIG_FILE"
echo "parameter file: $PARAMETER_FILE"

cpu_air_prover \
  --out_file="$PROOF_JSON" \
  --private_input_file="$AIR_PRIVATE_INPUT" \
  --public_input_file="$AIR_PUBLIC_INPUT" \
  --prover_config_file="$PROVER_CONFIG_FILE" \
  --parameter_file="$PARAMETER_FILE" \
  2>&1 | tee "$PROVE_LOG"

if [[ ! -f "$PROOF_JSON" ]]; then
  echo "cpu_air_prover completed but proof JSON is missing: $PROOF_JSON" >&2
  exit 1
fi

if [[ "$SKIP_VERIFY" -ne 1 ]]; then
  echo "==> Verifying Stone tally proof"
  set +e
  cpu_air_verifier --in_file="$PROOF_JSON" 2>&1 | tee "$VERIFY_LOG"
  verifier_status=${PIPESTATUS[0]}
  set -e
  if [[ "$verifier_status" -ne 0 ]]; then
    echo "cpu_air_verifier failed with status $verifier_status" >&2
    exit "$verifier_status"
  fi
  echo "Verified proof successfully" | tee -a "$VERIFY_LOG"
else
  printf 'verification skipped\n' > "$VERIFY_LOG"
fi

node - "$PROOF_RUN_JSON" "$AIR_RUN_JSON" "$PROOF_JSON" "$PREPARED_JSON" "$INPUT_PATH" "$EXECUTABLE" "$RUNNER_SIERRA_JSON" "$PROVE_LOG" "$VERIFY_LOG" <<'NODE'
const fs = require('fs');
const [
  out,
  airRunJson,
  proofJson,
  preparedJson,
  inputPath,
  executable,
  runnerSierraJson,
  proveLog,
  verifyLog,
] = process.argv.slice(2);

const output = {
  circuit: 'tally',
  executable: 'tally_votes_stone',
  sourceExecutable: executable,
  runnerSierraJson,
  inputPath,
  proofProducer: 'stone',
  integritySubmissionReady: false,
  proofJson,
  preparedJson,
  stoneAirRunJson: airRunJson,
  proveLog,
  verifyLog,
};

fs.writeFileSync(out, `${JSON.stringify(output, null, 2)}\n`);
NODE

echo "Stone proof metadata written to: $PROOF_RUN_JSON"
