#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

usage() {
  cat <<'EOF'
Usage:
  tools/run-stone-proof.sh [--air-run <stone-air-run.json>] [--out-dir <dir>] [options]

Runs Stone cpu_air_prover over AIR files generated by tools/run-stone-air.sh,
then verifies the proof locally with cpu_air_verifier.

Options:
  --air-run <path>          stone-air-run.json. Default: target/stone-air/tally/stone-air-run.json
  --out-dir <dir>           Output directory. Default: sibling directory "stone-proof" next to --air-run
  --stone-prover-dir <dir>  Stone prover checkout. Default: $STONE_PROVER_DIR or ~/stone-prover
  --prover-config <path>    cpu_air_prover_config.json. Default: <stone-prover-dir>/cpu_air_prover_config.json
  --parameter-file <path>   cpu_air_params.json. Default: <stone-prover-dir>/cpu_air_params.json
  --skip-verify             Skip cpu_air_verifier.

Outputs:
  stone-proof.json
  stone-prove.log
  stone-verify.log
  proof-run.json
EOF
}

require_tool() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "$1 is required" >&2
    exit 1
  fi
}

json_field() {
  local file="$1"
  local field="$2"
  node -e '
const fs = require("fs");
const [file, field] = process.argv.slice(1);
const json = JSON.parse(fs.readFileSync(file, "utf8"));
const value = json[field];
if (typeof value !== "string" || value.length === 0) {
  process.exit(2);
}
process.stdout.write(value);
' "$file" "$field"
}

AIR_RUN_JSON=""
OUT_DIR=""
STONE_PROVER_DIR="${STONE_PROVER_DIR:-$HOME/stone-prover}"
PROVER_CONFIG_FILE=""
PARAMETER_FILE=""
SKIP_VERIFY=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --air-run)
      AIR_RUN_JSON="${2:-}"
      shift 2
      ;;
    --out-dir)
      OUT_DIR="${2:-}"
      shift 2
      ;;
    --stone-prover-dir)
      STONE_PROVER_DIR="${2:-}"
      shift 2
      ;;
    --prover-config)
      PROVER_CONFIG_FILE="${2:-}"
      shift 2
      ;;
    --parameter-file)
      PARAMETER_FILE="${2:-}"
      shift 2
      ;;
    --skip-verify)
      SKIP_VERIFY=1
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

AIR_RUN_JSON="${AIR_RUN_JSON:-$ROOT_DIR/target/stone-air/tally/stone-air-run.json}"
AIR_RUN_JSON="$(cd "$(dirname "$AIR_RUN_JSON")" && pwd)/$(basename "$AIR_RUN_JSON")"

if [[ ! -f "$AIR_RUN_JSON" ]]; then
  echo "missing Stone AIR metadata: $AIR_RUN_JSON" >&2
  echo "run npm run stone:air:tally first" >&2
  exit 1
fi

OUT_DIR="${OUT_DIR:-$(dirname "$AIR_RUN_JSON")/stone-proof}"
mkdir -p "$OUT_DIR"
OUT_DIR="$(cd "$OUT_DIR" && pwd)"

STONE_PROVER_DIR="$(cd "$STONE_PROVER_DIR" && pwd)"
PROVER_CONFIG_FILE="${PROVER_CONFIG_FILE:-$STONE_PROVER_DIR/cpu_air_prover_config.json}"
PARAMETER_FILE="${PARAMETER_FILE:-$STONE_PROVER_DIR/cpu_air_params.json}"

require_tool node
require_tool cpu_air_prover
if [[ "$SKIP_VERIFY" -ne 1 ]]; then
  require_tool cpu_air_verifier
fi

if [[ ! -f "$PROVER_CONFIG_FILE" ]]; then
  echo "missing prover config file: $PROVER_CONFIG_FILE" >&2
  exit 1
fi

if [[ ! -f "$PARAMETER_FILE" ]]; then
  echo "missing parameter file: $PARAMETER_FILE" >&2
  exit 1
fi

AIR_PUBLIC_INPUT="$(json_field "$AIR_RUN_JSON" airPublicInput)"
AIR_PRIVATE_INPUT="$(json_field "$AIR_RUN_JSON" airPrivateInput)"
PREPARED_JSON="$(json_field "$AIR_RUN_JSON" preparedJson)"
INPUT_PATH="$(json_field "$AIR_RUN_JSON" inputPath)"
EXECUTABLE="$(json_field "$AIR_RUN_JSON" executable)"
RUNNER_SIERRA_JSON="$(json_field "$AIR_RUN_JSON" runnerSierraJson)"

if [[ ! -f "$AIR_PUBLIC_INPUT" ]]; then
  echo "missing AIR public input: $AIR_PUBLIC_INPUT" >&2
  exit 1
fi

if [[ ! -f "$AIR_PRIVATE_INPUT" ]]; then
  echo "missing AIR private input: $AIR_PRIVATE_INPUT" >&2
  exit 1
fi

PROOF_JSON="$OUT_DIR/stone-proof.json"
PROVE_LOG="$OUT_DIR/stone-prove.log"
VERIFY_LOG="$OUT_DIR/stone-verify.log"
PROOF_RUN_JSON="$OUT_DIR/proof-run.json"

echo "==> Proving Stone tally AIR"
echo "AIR run: $AIR_RUN_JSON"
echo "prover config: $PROVER_CONFIG_FILE"
echo "parameter file: $PARAMETER_FILE"

cpu_air_prover \
  --out_file="$PROOF_JSON" \
  --private_input_file="$AIR_PRIVATE_INPUT" \
  --public_input_file="$AIR_PUBLIC_INPUT" \
  --prover_config_file="$PROVER_CONFIG_FILE" \
  --parameter_file="$PARAMETER_FILE" \
  2>&1 | tee "$PROVE_LOG"

if [[ ! -f "$PROOF_JSON" ]]; then
  echo "cpu_air_prover completed but proof JSON is missing: $PROOF_JSON" >&2
  exit 1
fi

if [[ "$SKIP_VERIFY" -ne 1 ]]; then
  echo "==> Verifying Stone tally proof"
  set +e
  cpu_air_verifier --in_file="$PROOF_JSON" 2>&1 | tee "$VERIFY_LOG"
  verifier_status=${PIPESTATUS[0]}
  set -e
  if [[ "$verifier_status" -ne 0 ]]; then
    echo "cpu_air_verifier failed with status $verifier_status" >&2
    exit "$verifier_status"
  fi
  echo "Verified proof successfully" | tee -a "$VERIFY_LOG"
else
  printf 'verification skipped\n' > "$VERIFY_LOG"
fi

node - "$PROOF_RUN_JSON" "$AIR_RUN_JSON" "$PROOF_JSON" "$PREPARED_JSON" "$INPUT_PATH" "$EXECUTABLE" "$RUNNER_SIERRA_JSON" "$PROVE_LOG" "$VERIFY_LOG" <<'NODE'
const fs = require('fs');
const [
  out,
  airRunJson,
  proofJson,
  preparedJson,
  inputPath,
  executable,
  runnerSierraJson,
  proveLog,
  verifyLog,
] = process.argv.slice(2);

const output = {
  circuit: 'tally',
  executable: 'tally_votes_stone',
  sourceExecutable: executable,
  runnerSierraJson,
  inputPath,
  proofProducer: 'stone',
  integritySubmissionReady: false,
  proofJson,
  preparedJson,
  stoneAirRunJson: airRunJson,
  proveLog,
  verifyLog,
};

fs.writeFileSync(out, `${JSON.stringify(output, null, 2)}\n`);
NODE

echo "Stone proof metadata written to: $PROOF_RUN_JSON"
