#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

usage() {
  cat <<'EOF'
Usage:
  tools/run-stone-proof.sh [--air-run <stone-air-run.json>] [--out-dir <dir>] [options]

Runs Stone cpu_air_prover over AIR files generated by tools/run-stone-air.sh,
then verifies the proof locally with cpu_air_verifier.

Options:
  --air-run <path>          stone-air-run.json. Default: target/stone-air/tally-native/stone-air-run.json
  --out-dir <dir>           Output directory. Default: sibling directory "stone-proof" next to --air-run
  --stone-prover-dir <dir>  Stone prover checkout. Default: $STONE_PROVER_DIR or ~/stone-prover
  --prover-config <path>    cpu_air_prover_config.json. Auto-detected if omitted.
  --parameter-file <path>   cpu_air_params.json. Auto-detected if omitted.
                            If omitted, a matching params file is generated
                            from AIR n_steps under --out-dir.
  --no-annotations          Do not pass --generate_annotations to cpu_air_prover.
                            Integrity split calldata generation requires annotations.
  --skip-verify             Skip cpu_air_verifier.

Outputs:
  stone-proof.json
  stone-proof.prover-annotations.json
  stone-verifier-annotations.txt
  stone-verifier-extra-output.txt
  stone-prove.log
  stone-verify.log
  proof-run.json
EOF
}

require_tool() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "$1 is required" >&2
    exit 1
  fi
}

json_field() {
  local file="$1"
  local field="$2"
  node -e '
const fs = require("fs");
const [file, field] = process.argv.slice(1);
const json = JSON.parse(fs.readFileSync(file, "utf8"));
const value = json[field];
if (typeof value !== "string" || value.length === 0) {
  process.exit(2);
}
process.stdout.write(value);
' "$file" "$field"
}

json_field_optional() {
  local file="$1"
  local field="$2"
  node -e '
const fs = require("fs");
const [file, field] = process.argv.slice(1);
const json = JSON.parse(fs.readFileSync(file, "utf8"));
const value = json[field];
if (typeof value === "string" && value.length > 0) {
  process.stdout.write(value);
}
' "$file" "$field"
}

validate_air_layout() {
  local public_input_file="$1"
  node - "$public_input_file" <<'NODE'
const fs = require('fs');
const publicInputFile = process.argv[2];
const json = JSON.parse(fs.readFileSync(publicInputFile, 'utf8'));
const layout = String(json.layout ?? '');
const segments = json.mem_segment_addresses ?? json.memory_segments ?? {};
const missing = [];

if (layout === 'all_cairo' || layout === 'all_cairo_stwo') {
  for (const segment of ['add_mod', 'mul_mod']) {
    if (!Object.prototype.hasOwnProperty.call(segments, segment)) {
      missing.push(segment);
    }
  }
}

if (missing.length > 0) {
  console.error(
    `Stone AIR layout '${layout}' is missing builtin segment(s): ${missing.join(', ')}.`
  );
  console.error('Regenerate the AIR with a layout that matches this Stone wrapper, for example:');
  console.error('  npm run stone:air:tally -- --out-dir <new-dir>');
  console.error('Then rerun stone:prove:tally against the new stone-air-run.json.');
  process.exit(2);
}
NODE
}

resolve_stone_config_file() {
  local explicit_path="$1"
  local file_name="$2"
  local candidates=()

  if [[ -n "$explicit_path" ]]; then
    candidates+=("$explicit_path")
  else
    candidates+=(
      "$STONE_PROVER_DIR/$file_name"
      "$STONE_PROVER_DIR/e2e_test/Cairo/$file_name"
      "$STONE_PROVER_DIR/e2e_test/CairoZero/$file_name"
    )

    if [[ -n "${INTEGRITY_DIR:-}" ]]; then
      candidates+=("$INTEGRITY_DIR/examples/proofs/$file_name")
    fi
    if [[ -n "${HOME:-}" ]]; then
      candidates+=("$HOME/integrity/examples/proofs/$file_name")
    fi
  fi

  local candidate
  for candidate in "${candidates[@]}"; do
    if [[ -f "$candidate" ]]; then
      printf '%s/%s\n' "$(cd "$(dirname "$candidate")" && pwd)" "$(basename "$candidate")"
      return 0
    fi
  done

  echo "${explicit_path:-$STONE_PROVER_DIR/$file_name}"
  return 1
}

AIR_RUN_JSON=""
OUT_DIR=""
STONE_PROVER_DIR="${STONE_PROVER_DIR:-$HOME/stone-prover}"
PROVER_CONFIG_FILE=""
PARAMETER_FILE=""
PARAMETER_FILE_EXPLICIT=0
SKIP_VERIFY=0
GENERATE_ANNOTATIONS=1

while [[ $# -gt 0 ]]; do
  case "$1" in
    --air-run)
      AIR_RUN_JSON="${2:-}"
      shift 2
      ;;
    --out-dir)
      OUT_DIR="${2:-}"
      shift 2
      ;;
    --stone-prover-dir)
      STONE_PROVER_DIR="${2:-}"
      shift 2
      ;;
    --prover-config)
      PROVER_CONFIG_FILE="${2:-}"
      shift 2
      ;;
    --parameter-file)
      PARAMETER_FILE="${2:-}"
      PARAMETER_FILE_EXPLICIT=1
      shift 2
      ;;
    --skip-verify)
      SKIP_VERIFY=1
      shift
      ;;
    --no-annotations)
      GENERATE_ANNOTATIONS=0
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

AIR_RUN_JSON="${AIR_RUN_JSON:-$ROOT_DIR/target/stone-air/tally-native/stone-air-run.json}"
AIR_RUN_JSON="$(cd "$(dirname "$AIR_RUN_JSON")" && pwd)/$(basename "$AIR_RUN_JSON")"

if [[ ! -f "$AIR_RUN_JSON" ]]; then
  echo "missing Stone AIR metadata: $AIR_RUN_JSON" >&2
  echo "run npm run stone:air:tally first" >&2
  exit 1
fi

OUT_DIR="${OUT_DIR:-$(dirname "$AIR_RUN_JSON")/stone-proof}"
mkdir -p "$OUT_DIR"
OUT_DIR="$(cd "$OUT_DIR" && pwd)"

if [[ -d "$STONE_PROVER_DIR" ]]; then
  STONE_PROVER_DIR="$(cd "$STONE_PROVER_DIR" && pwd)"
fi
PROVER_CONFIG_FILE="$(resolve_stone_config_file "$PROVER_CONFIG_FILE" cpu_air_prover_config.json || true)"
PARAMETER_FILE="$(resolve_stone_config_file "$PARAMETER_FILE" cpu_air_params.json || true)"

require_tool node
require_tool cpu_air_prover
if [[ "$SKIP_VERIFY" -ne 1 ]]; then
  require_tool cpu_air_verifier
fi

if [[ ! -f "$PROVER_CONFIG_FILE" ]]; then
  echo "missing prover config file: $PROVER_CONFIG_FILE" >&2
  echo "pass --prover-config or set STONE_PROVER_DIR to a Stone checkout" >&2
  exit 1
fi

if [[ ! -f "$PARAMETER_FILE" ]]; then
  echo "missing parameter file: $PARAMETER_FILE" >&2
  echo "pass --parameter-file or set STONE_PROVER_DIR to a Stone checkout" >&2
  exit 1
fi

AIR_PUBLIC_INPUT="$(json_field "$AIR_RUN_JSON" airPublicInput)"
AIR_PRIVATE_INPUT="$(json_field "$AIR_RUN_JSON" airPrivateInput)"
PREPARED_JSON="$(json_field "$AIR_RUN_JSON" preparedJson)"
INPUT_PATH="$(json_field "$AIR_RUN_JSON" inputPath)"
EXECUTABLE="$(json_field "$AIR_RUN_JSON" executable)"
RUNNER_SIERRA_JSON="$(json_field "$AIR_RUN_JSON" runnerSierraJson)"
CIRCUIT="$(json_field_optional "$AIR_RUN_JSON" circuit)"
CIRCUIT="${CIRCUIT:-tally}"
STONE_EXECUTABLE="$(json_field_optional "$AIR_RUN_JSON" stoneExecutable)"
STONE_EXECUTABLE="${STONE_EXECUTABLE:-tally_votes_stone}"

if [[ ! -f "$AIR_PUBLIC_INPUT" ]]; then
  echo "missing AIR public input: $AIR_PUBLIC_INPUT" >&2
  exit 1
fi

if [[ ! -f "$AIR_PRIVATE_INPUT" ]]; then
  echo "missing AIR private input: $AIR_PRIVATE_INPUT" >&2
  exit 1
fi

validate_air_layout "$AIR_PUBLIC_INPUT"

if [[ "$PARAMETER_FILE_EXPLICIT" -ne 1 ]]; then
  BASE_PARAMETER_FILE="$PARAMETER_FILE"
  PARAMETER_FILE="$OUT_DIR/cpu_air_params.generated.json"
  PARAMETER_METADATA_FILE="$OUT_DIR/cpu_air_params.generated.metadata.json"
  echo "==> Generating Stone params for AIR trace size"
  node "$ROOT_DIR/tools/generate-stone-params.mjs" \
    --base "$BASE_PARAMETER_FILE" \
    --air-public-input "$AIR_PUBLIC_INPUT" \
    --out "$PARAMETER_FILE" \
    --metadata-out "$PARAMETER_METADATA_FILE" \
    --text
fi

PROOF_JSON="$OUT_DIR/stone-proof.json"
PROVER_ANNOTATED_PROOF_JSON="$OUT_DIR/stone-proof.prover-annotations.json"
VERIFIER_ANNOTATION_FILE="$OUT_DIR/stone-verifier-annotations.txt"
VERIFIER_EXTRA_OUTPUT_FILE="$OUT_DIR/stone-verifier-extra-output.txt"
PROVE_LOG="$OUT_DIR/stone-prove.log"
VERIFY_LOG="$OUT_DIR/stone-verify.log"
PROOF_RUN_JSON="$OUT_DIR/proof-run.json"

echo "==> Proving Stone $CIRCUIT AIR"
echo "AIR run: $AIR_RUN_JSON"
echo "stone executable: $STONE_EXECUTABLE"
echo "prover config: $PROVER_CONFIG_FILE"
echo "parameter file: $PARAMETER_FILE"
if [[ "$GENERATE_ANNOTATIONS" -eq 1 ]]; then
  echo "annotations: enabled"
else
  echo "annotations: disabled"
fi

PROVER_ARGS=(
  --out_file="$PROOF_JSON"
  --private_input_file="$AIR_PRIVATE_INPUT"
  --public_input_file="$AIR_PUBLIC_INPUT"
  --prover_config_file="$PROVER_CONFIG_FILE"
  --parameter_file="$PARAMETER_FILE"
)
if [[ "$GENERATE_ANNOTATIONS" -eq 1 ]]; then
  PROVER_ARGS+=(--generate_annotations)
fi

cpu_air_prover "${PROVER_ARGS[@]}" 2>&1 | tee "$PROVE_LOG"

if [[ ! -f "$PROOF_JSON" ]]; then
  echo "cpu_air_prover completed but proof JSON is missing: $PROOF_JSON" >&2
  exit 1
fi

if [[ "$SKIP_VERIFY" -ne 1 ]]; then
  echo "==> Verifying Stone $CIRCUIT proof"
  VERIFIER_ARGS=(--in_file="$PROOF_JSON")
  if [[ "$GENERATE_ANNOTATIONS" -eq 1 ]]; then
    VERIFIER_ARGS+=(
      --annotation_file="$VERIFIER_ANNOTATION_FILE"
      --extra_output_file="$VERIFIER_EXTRA_OUTPUT_FILE"
    )
  fi
  set +e
  cpu_air_verifier "${VERIFIER_ARGS[@]}" 2>&1 | tee "$VERIFY_LOG"
  verifier_status=${PIPESTATUS[0]}
  set -e
  if [[ "$verifier_status" -ne 0 ]]; then
    echo "cpu_air_verifier failed with status $verifier_status" >&2
    exit "$verifier_status"
  fi
  echo "Verified proof successfully" | tee -a "$VERIFY_LOG"
  if [[ "$GENERATE_ANNOTATIONS" -eq 1 ]]; then
    if [[ ! -s "$VERIFIER_ANNOTATION_FILE" ]]; then
      echo "cpu_air_verifier completed but verifier annotation file is missing or empty: $VERIFIER_ANNOTATION_FILE" >&2
      exit 1
    fi
    if [[ ! -f "$VERIFIER_EXTRA_OUTPUT_FILE" ]]; then
      echo "cpu_air_verifier completed but verifier extra-output file is missing: $VERIFIER_EXTRA_OUTPUT_FILE" >&2
      exit 1
    fi
    node - "$PROOF_JSON" "$PROVER_ANNOTATED_PROOF_JSON" "$VERIFIER_ANNOTATION_FILE" "$VERIFIER_EXTRA_OUTPUT_FILE" <<'NODE'
const fs = require('fs');
const [proofJson, proverAnnotatedProofJson, verifierAnnotationFile, verifierExtraOutputFile] =
  process.argv.slice(2);

function readLines(path) {
  const lines = fs.readFileSync(path, 'utf8').split(/\r?\n/);
  if (lines.at(-1) === '') {
    lines.pop();
  }
  return lines;
}

const proof = JSON.parse(fs.readFileSync(proofJson, 'utf8'));
fs.copyFileSync(proofJson, proverAnnotatedProofJson);
proof.annotations = readLines(verifierAnnotationFile);
proof.extra_annotations = readLines(verifierExtraOutputFile);
fs.writeFileSync(proofJson, `${JSON.stringify(proof, null, 2)}\n`);
NODE
    echo "Verifier annotations merged into: $PROOF_JSON" | tee -a "$VERIFY_LOG"
  fi
else
  printf 'verification skipped\n' > "$VERIFY_LOG"
fi

node - "$PROOF_RUN_JSON" "$AIR_RUN_JSON" "$PROOF_JSON" "$PREPARED_JSON" "$INPUT_PATH" "$EXECUTABLE" "$RUNNER_SIERRA_JSON" "$PROVE_LOG" "$VERIFY_LOG" "$GENERATE_ANNOTATIONS" "$PROVER_ANNOTATED_PROOF_JSON" "$VERIFIER_ANNOTATION_FILE" "$VERIFIER_EXTRA_OUTPUT_FILE" <<'NODE'
const fs = require('fs');
const [
  out,
  airRunJson,
  proofJson,
  preparedJson,
  inputPath,
  executable,
  runnerSierraJson,
  proveLog,
  verifyLog,
  generateAnnotations,
  proverAnnotatedProofJson,
  verifierAnnotationFile,
  verifierExtraOutputFile,
] = process.argv.slice(2);

const airRun = JSON.parse(fs.readFileSync(airRunJson, 'utf8'));
const proof = JSON.parse(fs.readFileSync(proofJson, 'utf8'));
const verifierAnnotationsPresent =
  fs.existsSync(verifierAnnotationFile) && fs.statSync(verifierAnnotationFile).size > 0;
const verifierExtraOutputPresent =
  fs.existsSync(verifierExtraOutputFile) && fs.statSync(verifierExtraOutputFile).size > 0;
const output = {
  circuit: airRun.circuit ?? 'tally',
  executable: airRun.stoneExecutable ?? 'tally_votes_stone',
  sourceExecutable: executable,
  runnerSierraJson,
  inputPath,
  proofProducer: 'stone',
  integritySubmissionReady: false,
  proofJson,
  preparedJson,
  stoneAirRunJson: airRunJson,
  proveLog,
  verifyLog,
  annotationsRequested: generateAnnotations === '1',
  annotationsPresent: Object.prototype.hasOwnProperty.call(proof, 'annotations'),
  verifierAnnotationsPresent,
  verifierExtraOutputPresent,
  verifierAnnotationFile,
  verifierExtraOutputFile,
  proverAnnotatedProofJson: fs.existsSync(proverAnnotatedProofJson)
    ? proverAnnotatedProofJson
    : undefined,
  annotationCount: Array.isArray(proof.annotations) ? proof.annotations.length : 0,
  extraAnnotationCount: Array.isArray(proof.extra_annotations) ? proof.extra_annotations.length : 0,
};

fs.writeFileSync(out, `${JSON.stringify(output, null, 2)}\n`);
NODE

echo "Stone proof metadata written to: $PROOF_RUN_JSON"
